/** Generated by [postcss-d-ts](https://github.com/askirmas/postcss-d-ts) */
declare const identifiersMap: CssIdentifiersMap

export default identifiersMap

export type CssIdentifiersMap = {
  "camelCaseRules": string|undefined
  "storybook-button": string|undefined
  "storybook-button--large": string|undefined
  "storybook-button--medium": string|undefined
  "storybook-button--primary": string|undefined
  "storybook-button--secondary": string|undefined
  "storybook-button--small": string|undefined
}
